### ISSUE TITLE
Not really clear how to integrate with your code

### ISSUE THREAD

**Issue by tadteo** [addy1997/actor_ign_plugins#1]
Hi,
I don't understand how to integrate your code to the rest of the plugins_ws.
Should I clone your code inside the src folder?
You explain how to create a  package but which are the dependencies of your code?

Thank you in advance
Matteo

**Comment by addy1997** [comment]
> Hi,
> I don't understand how to integrate your code to the rest of the plugins_ws.
> Should I clone your code inside the src folder?
> You explain how to create a package but which are the dependencies of your code?
> 
> Thank you in advance
> Matteo

No, don't clone this repository into the src dir of the folder. Apologies 

Please follow these steps

1. `mkdir -p ~/plugins_ws/src`

2. `cd ~/plugins_ws/src`

3. `catkin_create_pkg actor_plugins rclcpp`

4.  Follow these commands
```
cd ~/actor_plugins
 mkdir src
 cd src
```
Now move these files  **ign_gazebo_ros_path_follow_actor.cc and ign_gazebo_ros_path_follow_actor.hh** into the src directory.


5.  In the CMakeLists.txt file which you get from the previous step, add these lines at the end
```
set(IGN_PLUGIN_VER 0)
ign_find_package(ignition-plugin0 REQUIRED COMPONENTS register)
# Add sources for each plugin to be registered.
add_library(SampleSystem SampleSystem.cc SampleSystem2.cc)
set_property(TARGET SampleSystem PROPERTY CXX_STANDARD 17)
target_link_libraries(SampleSystem
  ignition-common${IGN_COMMON_VER}::ignition-common${IGN_COMMON_VER}
  ignition-plugin${IGN_PLUGIN_VER}::ignition-plugin${IGN_PLUGIN_VER}
)
```

6. Once the CMakeLists.txt file is edited, save it. Now follow these commands

cd ~/plugins_ws/src
```
sudo apt-get update
sudo apt install libignition-plugin-dev
sudo apt-get install libignition-gazebo3-dev
sudo apt-get install libignition-cmake2-dev
```

7. Now follow these commands
```
cd ~/actor_plugins/
mkdir build/
cd build/
cmake ..
make
```

8. `export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=`pwd`/build`

This should generate the _.so_ file

**Comment by addy1997** [comment]
@tadteo , I have also updated the readme with some links to create a ros2 package.

**Comment by tadteo** [comment]
That's great, thank you.
Anyway, I was looking and the default building system for ROS2 is colcon can you update the README accordingly?
Moreover, also in the readme, it's better to add the guide to install the specific version of this package. 
Maybe you can convert this folder into an actual package?

**Comment by addy1997** [comment]
Yes, I will do it.

**Comment by tadteo** [comment]
Yeah but colcon is just a wrapper for CMake. So it should work the same

Anyway, even using CMake I got this error
```
CMake Error at CMakeLists.txt:41 (add_library):
 Target "ign_gazebo_ros_path_follow_actor" links to target
  "ignition-common::ignition-common" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
```
Any clue on how to solve it?

**Comment by addy1997** [comment]
Well, I didn't get this error but I think installing common  should solve it. 

Install libignition-common-dev by entering the following commands in the terminal:

```
sudo apt update
sudo apt install libignition-common-dev
```

**Comment by addy1997** [comment]
Hope you were able to resolve the issue. I am closing this for now.
